services:
  backend-bot:
    container_name: backend-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./db
        target: /usr/src/app/db
      - /var/lib/marzban/certs/:/usr/src/app/uvicorn/ssl
      - ./backend.yml:/usr/src/app/backend.yml
    ports:
       - '127.0.0.1:5001:5001'
    networks:
      - backend-network
    restart: unless-stopped
networks:
  backend-network:
    name: backend-network
    driver: bridge
    external: true