import { useEffect, useState } from "react";
import { CheckCircle2, Database, KeyRound, Network, RefreshCw, XCircle } from "lucide-react";
import { api } from "../api";
import { Badge, Button, Card } from "../components/ui";

type Health = { database: { ok: boolean; driver?: string }; ggsel: { ok?: boolean; token_valid_until?: number; error?: string }; digiseller: { ok?: boolean; token_valid_until?: number; permissions?: object; error?: string }; checkpoints?: { provider: string; stream: string; last_success_at: string | null; gap_detected: boolean; detail: string | null }[]; outbox?: Record<string, number> };
export default function IntegrationsPage() {
  const [health, setHealth] = useState<Health | null>(null); const [busy, setBusy] = useState(false);
  const load = async () => { setBusy(true); try { setHealth(await api<Health>("/store/api/v1/integration-health")); } finally { setBusy(false); } };
  useEffect(() => { load(); }, []);
  const service = (name: string, value?: { ok?: boolean; error?: string; token_valid_until?: number }) => <Card><div className="flex items-start justify-between"><div className="flex gap-3"><span className="grid h-9 w-9 place-items-center rounded-md border"><Network className="h-4 w-4" /></span><div><h3 className="font-medium">{name}</h3><p className="muted">{value?.ok ? "Authentication active" : value?.error || "Checking…"}</p></div></div>{value?.ok ? <CheckCircle2 className="h-5 w-5 text-success" /> : <XCircle className="h-5 w-5 text-danger" />}</div>{value?.token_valid_until && <p className="mt-4 text-xs text-muted-foreground"><KeyRound className="mr-1 inline h-3 w-3" />Token refresh before {new Date(value.token_valid_until * 1000).toLocaleTimeString()}</p>}</Card>;
  return <div className="space-y-5"><div className="flex items-end justify-between"><div><h2 className="page-title">Integration health</h2><p className="muted mt-1">Credentials, checkpoints, gaps and delivery queues.</p></div><Button onClick={load}><RefreshCw className={`h-4 w-4 ${busy ? "animate-spin" : ""}`} />Refresh</Button></div><div className="grid gap-3 lg:grid-cols-3"><Card><div className="flex justify-between"><div className="flex gap-3"><span className="grid h-9 w-9 place-items-center rounded-md border"><Database className="h-4 w-4" /></span><div><h3 className="font-medium">PostgreSQL</h3><p className="muted">{health?.database.driver || "Database"}</p></div></div><Badge tone={health?.database.ok ? "success" : "danger"}>{health?.database.ok ? "healthy" : "offline"}</Badge></div></Card>{service("GGSel V1", health?.ggsel)}{service("Digiseller", health?.digiseller)}</div><Card><h3 className="font-medium">Order checkpoints</h3><div className="mt-4 overflow-x-auto"><table><thead><tr><th>Provider</th><th>Stream</th><th>Last success</th><th>Continuity</th><th>Detail</th></tr></thead><tbody>{health?.checkpoints?.map((row) => <tr key={`${row.provider}:${row.stream}`}><td>{row.provider}</td><td>{row.stream}</td><td>{row.last_success_at ? new Date(row.last_success_at).toLocaleString() : "—"}</td><td><Badge tone={row.gap_detected ? "danger" : "success"}>{row.gap_detected ? "gap possible" : "continuous"}</Badge></td><td className="text-muted-foreground">{row.detail || "—"}</td></tr>)}</tbody></table></div></Card>{health?.digiseller.permissions && <Card><h3 className="font-medium">Digiseller permissions</h3><pre className="mt-3 overflow-auto rounded-md bg-black/25 p-3 text-xs text-muted-foreground">{JSON.stringify(health.digiseller.permissions, null, 2)}</pre></Card>}</div>;
}
